<?xml version="1.0" encoding="utf-8"?><Database Name="Company" Class="DataLeadDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-5V4FCOT\SQLEXPRESS;Initial Catalog=Company;Integrated Security=True" SettingsObjectName="Company_DataBase.Properties.Settings" SettingsPropertyName="CompanyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Lead" Member="Leads">
    <Type Name="Lead">
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="L_SSN" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="university" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="L_Email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>